import React from 'react';

const Header: React.FC = () => {
  return (
    <header className="text-center my-8 md:my-12">
      <h1 className="text-4xl md:text-6xl font-bold tracking-tighter">
        AI Story <span className="text-cyan-400">Typer</span>
      </h1>
      <p className="text-slate-400 mt-2 max-w-2xl mx-auto">
        Type the story generated by AI. Your mistakes will become part of the plot!
      </p>
    </header>
  );
};

export default Header;